apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-agent-config
  namespace: logging
data:
  elastic-agent.yml: |
    outputs:
      default:
        type: elasticsearch
        hosts:
          - https://logs-es-http.logging.svc:9200
        username: ${ELASTIC_USERNAME}
        password: ${ELASTIC_PASSWORD}
        ssl:
          verification_mode: none

    inputs:
      - id: kubernetes-container-logs
        type: filestream
        use_output: default

        data_stream:
          type: logs
          dataset: kubernetes.container_logs
          namespace: default

        prospector.scanner.symlinks: true

        parsers:
          - container:
              format: auto

        paths:
          - /var/log/containers/*.log