apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-agent
  namespace: logging
spec:
  selector:
    matchLabels:
      app: elastic-agent
  template:
    metadata:
      labels:
        app: elastic-agent
    spec:
      serviceAccountName: elastic-agent

      containers:
        - name: elastic-agent
          image: docker.elastic.co/elastic-agent/elastic-agent:9.1.4
          imagePullPolicy: IfNotPresent

          env:
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-agent-credentials
                  key: username

            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-agent-credentials
                  key: password
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          volumeMounts:
            - name: config
              mountPath: /usr/share/elastic-agent/elastic-agent.yml
              subPath: elastic-agent.yml
              readOnly: true

            - name: container-logs
              mountPath: /var/log/containers
              readOnly: true

            - name: pod-logs
              mountPath: /var/log/pods
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: elastic-agent-config

        - name: container-logs
          hostPath:
            path: /var/log/containers

        - name: pod-logs
          hostPath:
            path: /var/log/pods

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: logging